/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ai/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Search */
        post: operations["ai_search_api_ai_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fliclists/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_fliclists__get"];
        put?: never;
        /** Create Preset */
        post: operations["create_preset_fliclists__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fliclists/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memory */
        get: operations["list_memory_fliclists_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fliclists/{preset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Preset */
        delete: operations["delete_preset_fliclists__preset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Movies */
        get: operations["list_movies_movies__get"];
        put?: never;
        /** Create Movie */
        post: operations["create_movie_movies__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Flags */
        get: operations["list_flags_movies_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pick */
        get: operations["get_pick_movies_picks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Movies */
        get: operations["search_movies_movies_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/search/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Llm Search Movies */
        post: operations["llm_search_movies_movies_search_llm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/{movie_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Movie */
        patch: operations["update_movie_movies__movie_id__patch"];
        trace?: never;
    };
    "/movies/{movie_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Movie Detail */
        get: operations["movie_detail_movies__movie_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/{movie_id}/flag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flag Movie */
        post: operations["flag_movie_movies__movie_id__flag_post"];
        /** Clear Flag */
        delete: operations["clear_flag_movies__movie_id__flag_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/{movie_id}/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Movie Lookup */
        get: operations["movie_lookup_movies__movie_id__lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/{movie_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_movies__movie_id__roles_get"];
        put?: never;
        /** Attach Role */
        post: operations["attach_role_movies__movie_id__roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List People */
        get: operations["list_people_people__get"];
        put?: never;
        /** Create Person */
        post: operations["create_person_people__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Movies Grid */
        get: operations["movies_grid_ui_movies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/movies/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Movies Health */
        get: operations["movies_health_ui_movies_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/movies/manual-add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual Add Movie */
        post: operations["manual_add_movie_ui_movies_manual_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/movies/manual-add/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual Add Preview */
        post: operations["manual_add_preview_ui_movies_manual_add_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/movies/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Movies Top */
        get: operations["movies_top_ui_movies_top_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/movies/{movie_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Movie Detail */
        get: operations["movie_detail_ui_movies__movie_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiSearchRequest */
        AiSearchRequest: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 24
             */
            page_size: number;
            /** Query */
            query: string;
        };
        /** AiSearchResponse */
        AiSearchResponse: {
            /** Explanation */
            explanation: string;
            facets: components["schemas"]["MovieFacets"];
            /** Items */
            items: components["schemas"]["MovieRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            plan: components["schemas"]["SearchPlan"];
            /** Total */
            total: number;
        };
        /** FlicFilters */
        FlicFilters: {
            /** Genres */
            genres?: string[];
            /** Moods */
            moods?: string[];
            /** Q */
            q?: string | null;
            /** Runtime Max */
            runtime_max?: number | null;
            /** Year Max */
            year_max?: number | null;
            /** Year Min */
            year_min?: number | null;
        };
        /** FlicMemoryRead */
        FlicMemoryRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Movie Id */
            movie_id: number;
        };
        /** FlicPresetCreate */
        FlicPresetCreate: {
            filters: components["schemas"]["FlicFilters"];
            /** Name */
            name: string;
        };
        /** FlicPresetRead */
        FlicPresetRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            filters: components["schemas"]["FlicFilters"];
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** GenreRead */
        GenreRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LlmMovieFilters */
        LlmMovieFilters: {
            /** Genres */
            genres?: string[];
            /** Moods */
            moods?: string[];
            /**
             * Order By
             * @default title_asc
             */
            order_by: string;
            /** Q */
            q?: string | null;
            /** Runtime Max */
            runtime_max?: number | null;
            /** Runtime Min */
            runtime_min?: number | null;
            /** Year Max */
            year_max?: number | null;
            /** Year Min */
            year_min?: number | null;
        };
        /** LlmMovieSearchRequest */
        LlmMovieSearchRequest: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 24
             */
            page_size: number;
            /** Query */
            query: string;
        };
        /** LlmMovieSearchResponse */
        LlmMovieSearchResponse: {
            facets: components["schemas"]["MovieFacets"];
            filters: components["schemas"]["LlmMovieFilters"];
            /** Items */
            items: components["schemas"]["MovieRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** ManualMovieCreate */
        ManualMovieCreate: {
            metadata?: components["schemas"]["ManualMovieMetadata"] | null;
            /** Title */
            title: string;
            /**
             * Vudu
             * @default false
             */
            vudu: boolean;
            /** Year */
            year?: number | null;
        };
        /** ManualMovieMetadata */
        ManualMovieMetadata: {
            /** Backdrop Url */
            backdrop_url?: string | null;
            /** Genres */
            genres?: string[];
            /** Imdb Id */
            imdb_id?: string | null;
            /** Keywords */
            keywords?: string[];
            /** Overview */
            overview?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Release Date */
            release_date?: string | null;
            /** Runtime */
            runtime?: number | null;
            /** Source */
            source?: string | null;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Where To Watch */
            where_to_watch?: string[];
        };
        /** ManualMoviePreviewResponse */
        ManualMoviePreviewResponse: {
            /** Backdrop Url */
            backdrop_url?: string | null;
            /** Genres */
            genres?: string[];
            /** Imdb Id */
            imdb_id?: string | null;
            /** Keywords */
            keywords?: string[];
            /** Overview */
            overview?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Release Date */
            release_date?: string | null;
            /** Runtime */
            runtime?: number | null;
            /** Source */
            source?: string | null;
            /** Title */
            title: string;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Where To Watch */
            where_to_watch?: string[];
            /** Year */
            year?: number | null;
        };
        /** MoodRead */
        MoodRead: {
            /** Description */
            description?: string | null;
            /** Emoji */
            emoji?: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** MovieCreate */
        MovieCreate: {
            /** Awards */
            awards?: string | null;
            /** Backdrop Url */
            backdrop_url?: string | null;
            /** Collection */
            collection?: string | null;
            /** Countries */
            countries?: string | string[] | null;
            /** Genres */
            genres?: string[];
            /** Imdb Id */
            imdb_id?: string | null;
            /** Imdb Rating */
            imdb_rating?: number | null;
            /** Imdb Votes */
            imdb_votes?: number | null;
            /** Languages */
            languages?: string | string[] | null;
            /** Metascore */
            metascore?: number | null;
            /** Moods */
            moods?: string[];
            /** Plot */
            plot?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Runtime */
            runtime?: number | null;
            /** Title */
            title: string;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Tomato Audience */
            tomato_audience?: number | null;
            /** Tomato Meter */
            tomato_meter?: number | null;
            /** Where To Watch */
            where_to_watch?: string | string[] | null;
            /** Year */
            year?: number | null;
        };
        /** MovieDetail */
        MovieDetail: {
            /** Awards */
            awards?: string | null;
            /** Backdrop Url */
            backdrop_url?: string | null;
            /** Collection */
            collection?: string | null;
            /** Countries */
            countries?: string | string[] | null;
            /** Countries Display */
            countries_display?: string[];
            /** Countries Iso */
            countries_iso?: string[];
            /**
             * Flagged
             * @default false
             */
            flagged: boolean;
            /** Genres */
            genres?: string[];
            /** Id */
            id: number;
            /** Imdb Id */
            imdb_id?: string | null;
            /** Imdb Rating */
            imdb_rating?: number | null;
            /** Imdb Votes */
            imdb_votes?: number | null;
            /** Languages */
            languages?: string | string[] | null;
            /** Languages Display */
            languages_display?: string[];
            /** Languages Iso */
            languages_iso?: string[];
            /** Last Omdb Fetch At */
            last_omdb_fetch_at?: string | null;
            /** Last Tmdb Fetch At */
            last_tmdb_fetch_at?: string | null;
            /** Metascore */
            metascore?: number | null;
            /** Moods */
            moods?: string[];
            /** Omdb Payload Sha */
            omdb_payload_sha?: string | null;
            /** Plot */
            plot?: string | null;
            /** Poster Theme */
            poster_theme?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Roles */
            roles?: components["schemas"]["RoleWithPersonRead"][];
            /** Rt Score */
            rt_score?: number | null;
            /** Runtime */
            runtime?: number | null;
            /** Similar */
            similar?: components["schemas"]["SimilarMovie"][];
            /** Title */
            title: string;
            /** Tmdb Etag */
            tmdb_etag?: string | null;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Tmdb Payload Sha */
            tmdb_payload_sha?: string | null;
            /** Tomato Audience */
            tomato_audience?: number | null;
            /** Tomato Meter */
            tomato_meter?: number | null;
            /** Top Billed */
            top_billed?: components["schemas"]["TopBilledEntry"][];
            /** Where To Watch */
            where_to_watch?: string[];
            /** Year */
            year?: number | null;
        };
        /** MovieFacets */
        MovieFacets: {
            /** Genres */
            genres?: {
                [key: string]: number;
            };
            /** Moods */
            moods?: {
                [key: string]: number;
            };
        };
        /** MovieFlagCreate */
        MovieFlagCreate: {
            /** Notes */
            notes?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** MovieFlagRead */
        MovieFlagRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Movie Id */
            movie_id: number;
            /** Notes */
            notes?: string | null;
            /** Reason */
            reason?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MovieLookupCandidate */
        MovieLookupCandidate: {
            /** Backdrop Url */
            backdrop_url?: string | null;
            /** Genres */
            genres?: string[];
            /** Imdb Id */
            imdb_id?: string | null;
            /** Keywords */
            keywords?: string[];
            /**
             * Overview
             * @default
             */
            overview: string;
            /** Poster Url */
            poster_url?: string | null;
            /** Release Date */
            release_date?: string | null;
            /** Runtime */
            runtime?: number | null;
            /**
             * Source
             * @default tmdb
             */
            source: string;
            /**
             * Synopsis
             * @default
             */
            synopsis: string;
            /** Title */
            title: string;
            /** Tmdb Id */
            tmdb_id: number;
            /** Where To Watch */
            where_to_watch?: string[];
            /** Year */
            year?: number | null;
        };
        /** MovieLookupResponse */
        MovieLookupResponse: {
            /** Items */
            items?: components["schemas"]["MovieLookupCandidate"][];
        };
        /** MovieRead */
        MovieRead: {
            /** Awards */
            awards?: string | null;
            /** Backdrop Url */
            backdrop_url?: string | null;
            /** Collection */
            collection?: string | null;
            /** Countries */
            countries?: string | string[] | null;
            /** Countries Iso */
            readonly countries_iso: string[];
            /**
             * Flagged
             * @default false
             */
            flagged: boolean;
            /** Genres */
            genres?: components["schemas"]["GenreRead"][];
            /** Id */
            id: number;
            /** Imdb Id */
            imdb_id?: string | null;
            /** Imdb Rating */
            imdb_rating?: number | null;
            /** Imdb Votes */
            imdb_votes?: number | null;
            /** Languages */
            languages?: string | string[] | null;
            /** Languages Iso */
            readonly languages_iso: string[];
            /** Last Omdb Fetch At */
            last_omdb_fetch_at?: string | null;
            /** Last Tmdb Fetch At */
            last_tmdb_fetch_at?: string | null;
            /** Metascore */
            metascore?: number | null;
            /** Moods */
            moods?: components["schemas"]["MoodRead"][];
            /** Omdb Payload Sha */
            omdb_payload_sha?: string | null;
            /** Plot */
            plot?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Runtime */
            runtime?: number | null;
            /** Title */
            title: string;
            /** Tmdb Etag */
            tmdb_etag?: string | null;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Tmdb Payload Sha */
            tmdb_payload_sha?: string | null;
            /** Tomato Audience */
            tomato_audience?: number | null;
            /** Tomato Meter */
            tomato_meter?: number | null;
            /** Where To Watch */
            where_to_watch?: string | string[] | null;
            /** Where To Watch List */
            readonly where_to_watch_list: string[];
            /** Year */
            year?: number | null;
        };
        /** MovieSearchResponse */
        MovieSearchResponse: {
            facets: components["schemas"]["MovieFacets"];
            /** Items */
            items: components["schemas"]["MovieRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** MovieUpdate */
        MovieUpdate: {
            /** Awards */
            awards?: string | null;
            /** Backdrop Url */
            backdrop_url?: string | null;
            /** Collection */
            collection?: string | null;
            /** Countries */
            countries?: string | string[] | null;
            /** Genres */
            genres?: string[] | null;
            /** Imdb Id */
            imdb_id?: string | null;
            /** Imdb Rating */
            imdb_rating?: number | null;
            /** Imdb Votes */
            imdb_votes?: number | null;
            /** Languages */
            languages?: string | string[] | null;
            /** Last Omdb Fetch At */
            last_omdb_fetch_at?: string | null;
            /** Last Tmdb Fetch At */
            last_tmdb_fetch_at?: string | null;
            /** Metascore */
            metascore?: number | null;
            /** Omdb Payload Sha */
            omdb_payload_sha?: string | null;
            /** Plot */
            plot?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /**
             * Resolve Flag
             * @default false
             */
            resolve_flag: boolean;
            /** Rt Score */
            rt_score?: number | null;
            /** Runtime */
            runtime?: number | null;
            /** Title */
            title?: string | null;
            /** Tmdb Etag */
            tmdb_etag?: string | null;
            /** Tmdb Id */
            tmdb_id?: number | null;
            /** Tmdb Payload Sha */
            tmdb_payload_sha?: string | null;
            /** Tomato Audience */
            tomato_audience?: number | null;
            /** Tomato Meter */
            tomato_meter?: number | null;
            /** Where To Watch */
            where_to_watch?: string[] | null;
            /** Year */
            year?: number | null;
        };
        /** PersonCreate */
        PersonCreate: {
            /** Imdb Id */
            imdb_id?: string | null;
            /** Name */
            name: string;
            /** Tmdb Id */
            tmdb_id?: number | null;
        };
        /** PersonListResponse */
        PersonListResponse: {
            /** Items */
            items: components["schemas"]["PersonRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PersonNested */
        PersonNested: {
            /** Id */
            id: number;
            /** Imdb Id */
            imdb_id?: string | null;
            /** Name */
            name: string;
            /** Tmdb Id */
            tmdb_id?: number | null;
        };
        /** PersonRead */
        PersonRead: {
            /** Id */
            id: number;
            /** Imdb Id */
            imdb_id?: string | null;
            /** Name */
            name: string;
            /** Tmdb Id */
            tmdb_id?: number | null;
        };
        /** RoleAttach */
        RoleAttach: {
            /** Billing Order */
            billing_order?: number | null;
            /** Character Name */
            character_name?: string | null;
            /** Person Id */
            person_id: number;
            role_type: components["schemas"]["RoleType"];
        };
        /** RoleRead */
        RoleRead: {
            /** Billing Order */
            billing_order?: number | null;
            /** Character Name */
            character_name?: string | null;
            /** Id */
            id: number;
            /** Movie Id */
            movie_id: number;
            person: components["schemas"]["PersonRead"];
            /** Person Id */
            person_id: number;
            role_type: components["schemas"]["RoleType"];
        };
        /**
         * RoleType
         * @enum {string}
         */
        RoleType: "ACTOR" | "DIRECTOR" | "WRITER";
        /** RoleWithPersonRead */
        RoleWithPersonRead: {
            /** Billing Order */
            billing_order?: number | null;
            /** Character Name */
            character_name?: string | null;
            /** Id */
            id: number;
            /** Movie Id */
            movie_id: number;
            person: components["schemas"]["PersonNested"];
            /** Person Id */
            person_id: number;
            /** Role Type */
            role_type: string;
        };
        /** SearchPlan */
        SearchPlan: {
            /** Genres */
            genres?: string[];
            /** Moods */
            moods?: string[];
            /**
             * Order By
             * @default title_asc
             */
            order_by: string;
            /** Q */
            q?: string | null;
            /** Runtime Max */
            runtime_max?: number | null;
            /** Runtime Min */
            runtime_min?: number | null;
            /** Year Max */
            year_max?: number | null;
            /** Year Min */
            year_min?: number | null;
        };
        /** SimilarMovie */
        SimilarMovie: {
            /** Flic Score */
            flic_score?: number | null;
            /** Id */
            id: number;
            /** Poster Theme */
            poster_theme?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Title */
            title: string;
            /** Year */
            year?: number | null;
        };
        /** TopBilledEntry */
        TopBilledEntry: {
            /** Character */
            character?: string | null;
            /** Imdb Id */
            imdb_id?: string | null;
            /** Name */
            name: string;
            /** Person Id */
            person_id?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ai_search_api_ai_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_fliclists__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlicPresetRead"][];
                };
            };
        };
    };
    create_preset_fliclists__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlicPresetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlicPresetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memory_fliclists_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlicMemoryRead"][];
                };
            };
        };
    };
    delete_preset_fliclists__preset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_movies_movies__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieRead"][];
                };
            };
        };
    };
    create_movie_movies__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovieCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flags_movies_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieFlagRead"][];
                };
            };
        };
    };
    get_pick_movies_picks_get: {
        parameters: {
            query?: {
                /** @description Desired mood name */
                mood?: string | null;
                /** @description Restrict to this genre */
                genre?: string | null;
                year_min?: string | null;
                year_max?: string | null;
                runtime_max?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_movies_movies_search_get: {
        parameters: {
            query?: {
                /** @description Case-insensitive search on movie title */
                q?: string | null;
                /** @description Earliest release year to include */
                year_min?: string | null;
                /** @description Latest release year to include */
                year_max?: string | null;
                /** @description Minimum runtime in minutes */
                runtime_min?: string | null;
                /** @description Maximum runtime in minutes */
                runtime_max?: string | null;
                /** @description Comma separated list of genre names */
                genres?: string | null;
                /** @description Comma separated list of mood names */
                moods?: string | null;
                order_by?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_search_movies_movies_search_llm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmMovieSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmMovieSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_movie_movies__movie_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovieUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    movie_detail_movies__movie_id__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flag_movie_movies__movie_id__flag_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovieFlagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieFlagRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_flag_movies__movie_id__flag_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    movie_lookup_movies__movie_id__lookup_get: {
        parameters: {
            query?: {
                /** @description Override title to search */
                title?: string | null;
                year?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_movies__movie_id__roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_role_movies__movie_id__roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAttach"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_people_people__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_person_people__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    movies_grid_ui_movies_get: {
        parameters: {
            query?: {
                q?: string | null;
                genres?: string | null;
                moods?: string | null;
                year_min?: string | null;
                year_max?: string | null;
                runtime_max?: string | null;
                page?: number;
                order_by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    movies_health_ui_movies_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    manual_add_movie_ui_movies_manual_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualMovieCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_add_preview_ui_movies_manual_add_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualMovieCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualMoviePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    movies_top_ui_movies_top_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    movie_detail_ui_movies__movie_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
